2025-01-31 18:56:05.509 [info] (Client) Pylance async client (2024.12.1) started with python extension (2024.22.2)
2025-01-31 18:56:05.824 [info] [Info  - 18:56:05] (24254) Server root directory: file:///home/fabian/.vscode/extensions/ms-python.vscode-pylance-2024.12.1/dist
2025-01-31 18:56:05.824 [info] [Info  - 18:56:05] (24254) Pylance language server 2024.12.1 (pyright version 1.1.389, commit ce1325fc) starting
2025-01-31 18:56:05.837 [info] [Info  - 18:56:05] (24254) Starting service instance "<default>"
2025-01-31 18:56:05.857 [info] [Info  - 18:56:05] (24254) Setting environmentName for service "<default>": "3.12.7 (global)"
2025-01-31 18:56:05.857 [info] [Info  - 18:56:05] (24254) Setting pythonPath for service "<default>": "/usr/bin/python"
2025-01-31 18:56:05.857 [info] [Info  - 18:56:05] (24254) No include entries specified; assuming /<default workspace root>
2025-01-31 18:56:05.858 [info] [Info  - 18:56:05] (24254) Auto-excluding **/node_modules
2025-01-31 18:56:05.858 [info] [Info  - 18:56:05] (24254) Auto-excluding **/__pycache__
2025-01-31 18:56:05.858 [info] [Info  - 18:56:05] (24254) Auto-excluding **/.*
2025-01-31 18:56:05.875 [info] [Info  - 18:56:05] (24254) Assuming Python version 3.13.1.final.0
2025-01-31 18:56:05.998 [info] [Error - 18:56:05] (24254) File or directory "/<default workspace root>" does not exist.
2025-01-31 18:56:05.998 [info] [Info  - 18:56:05] (24254) No source files found.
2025-01-31 18:56:06.021 [info] [Info  - 18:56:06] (24254) Setting environmentName for service "<default>": "3.12.7 (global)"
2025-01-31 18:56:06.021 [info] [Info  - 18:56:06] (24254) Setting pythonPath for service "<default>": "/usr/bin/python"
2025-01-31 18:56:06.021 [info] [Info  - 18:56:06] (24254) No include entries specified; assuming /<default workspace root>
2025-01-31 18:56:06.021 [info] [Info  - 18:56:06] (24254) Auto-excluding **/node_modules
2025-01-31 18:56:06.021 [info] [Info  - 18:56:06] (24254) Auto-excluding **/__pycache__
2025-01-31 18:56:06.021 [info] [Info  - 18:56:06] (24254) Auto-excluding **/.*
2025-01-31 18:56:06.039 [info] [Info  - 18:56:06] (24254) Assuming Python version 3.13.1.final.0
2025-01-31 18:56:06.066 [info] [Error - 18:56:06] (24254) File or directory "/<default workspace root>" does not exist.
2025-01-31 18:56:06.067 [info] [Info  - 18:56:06] (24254) No source files found.
2025-01-31 18:56:06.187 [info] [Info  - 18:56:06] (24254) Background analysis(1) root directory: file:///home/fabian/.vscode/extensions/ms-python.vscode-pylance-2024.12.1/dist
2025-01-31 18:56:06.188 [info] [Info  - 18:56:06] (24254) Background analysis(1) started
